services:
  banzo-builds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banzo_ubuntu_os_container
    image: banzo/website-vps:latest
    restart: always
    hostname: banzovps
    tty: true
    privileged: true
    stdin_open: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      # Mount your home directory or other paths for persistent storage
      - ~/data:/home/ubuntu/data
      - ubuntu-home:/home/ubuntu
   # ports:
      # Expose ports if you run any applications inside the container
      # - "8080:8080"
      # - "42:22"  # If you want to SSH into the container
    command: ["/bin/bash", "-c", "/home/ubuntu/startup.sh && tail -f /dev/null"]
   # command: ["/bin/bash", "-c", "tail -f /dev/null"]
    networks:
      - banzo-network
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: banzo-stg-env
    restart: always
    command: ["/bin/bash", "-c", "tunnel --no-autoupdate run --token $(cat /run/secrets/cloudflared_token)"]
    networks:
      - banzo-network
    secrets:
      - cloudflared_token

networks:
  banzo-network:
    driver: bridge

volumes:
  ubuntu-home:

secrets:
  cloudflared_token:
    file: ./cloudflared_token.txt
