services:
  banzo-playground:
    image: ubuntu:22.04
    container_name: banzo-playground
    restart: always
    command: /bin/bash
    volumes:
      - ubuntu-playground:/root
    tty: true
  banzo-builds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banzo_ubuntu_os_container
    image: banzo/website-vps:latest
    restart: always
    hostname: banzovps
    tty: true
    privileged: true
    stdin_open: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      # Mount your home directory or other paths for persistent storage
      - ~/data:/home/ubuntu/data
      #- ubuntu-home:/home/ubuntu
   # ports:
      # Expose ports if you run any applications inside the container
      # - "8080:8080"
      # - "42:22"  # If you want to SSH into the container
    command: ["/bin/bash", "-c", "/home/ubuntu/startup.sh && tail -f /dev/null"]
   # command: ["/bin/bash", "-c", "tail -f /dev/null"]
    
  tunnel:
    container_name: banzo_cfd
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiZTBhYjBkZDIxYjU2NGI4YzdkODllMjZjMTZmMjVmZTYiLCJ0IjoiMmQ3MWQxMjItMWUyNi00MmEzLWJiMDgtN2M4ZDI1YjljMDg3IiwicyI6IlkyUTJPRFJqWXpjdFptRTRNeTAwTmpBMkxXRmxOMlV0Tnpnek9HWmxZVE01T1dVMyJ9

networks:
  banzo-network:
    driver: bridge

volumes:
  ubuntu-playground:
